id: A4D374515
title: Elaborate and Concise Empowerments of the Substances, Symbols and Seven Emblems
  Extracted from the Three-Kāya Peaceful and Wrathful Deities of the Longsal Dorje
  Nyingpo
type: translation
pechas:
- ID7B6B77D
- I16D11B15
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:00:52.644798
  last_modified_at: 2023-01-04 13:00:52.644819
  collections:
  - Longsal Nyingpo Series
  - Works of Tibetan Masters
alignment_to_base:
  ID7B6B77D/33F8: 3F3A
  I16D11B15/2342: 3F3A
